# # Offense count: 6
# # This cop supports safe autocorrection (--autocorrect).
# # Configuration parameters: EnforcedStyle, IndentationWidth.
# # SupportedStyles: aligned, indented
# Layout/LineEndStringConcatenationIndentation:
#   Exclude:
#     - 'lib/puppet/provider/iis_application/webadministration.rb'
#     - 'lib/puppet/provider/iis_virtual_directory/webadministration.rb'
#     - 'spec/support/utilities/iis_site.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyleForEmptyBraces.
# SupportedStyles: space, no_space, compact
# SupportedStylesForEmptyBraces: space, no_space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

# Offense count: 6
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Exclude:
    - 'lib/puppet/provider/iis_application/webadministration.rb'
    - 'lib/puppet/provider/iis_application_pool/webadministration.rb'
    - 'lib/puppet/provider/iis_feature/default.rb'
    - 'lib/puppet/provider/iis_powershell.rb'
    - 'lib/puppet/provider/iis_site/webadministration.rb'
    - 'lib/puppet/provider/iis_virtual_directory/webadministration.rb'

# Offense count: 66
# This cop supports unsafe autocorrection (--autocorrect-all).
Lint/BooleanSymbol:
  Exclude:
    - 'lib/puppet/provider/iis_site/webadministration.rb'
    - 'lib/puppet/type/iis_application_pool.rb'
    - 'lib/puppet/type/iis_site.rb'
    - 'spec/acceptance/iis_application_pool_spec.rb'
    - 'spec/unit/puppet/type/iis_site_spec.rb'

# Offense count: 1
# Configuration parameters: AllowedMethods.
# AllowedMethods: enums
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'lib/puppet/provider/iis_site/webadministration.rb'

# Offense count: 1
# Configuration parameters: IgnoreLiteralBranches, IgnoreConstantBranches.
Lint/DuplicateBranch:
  Exclude:
    - 'lib/puppet/provider/iis_application/webadministration.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
Lint/ErbNewArguments:
  Exclude:
    - 'lib/puppet/provider/iis_powershell.rb'

# Offense count: 1
Lint/MixedRegexpCaptureTypes:
  Exclude:
    - 'lib/puppet/provider/iis_site/webadministration.rb'

# Offense count: 12
# This cop supports safe autocorrection (--autocorrect).
Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'spec/acceptance/iis_site_spec.rb'
    - 'spec/acceptance/iis_unicode_site_spec.rb'
    - 'spec/acceptance/iis_virtual_directory_spec.rb'
    - 'spec/acceptance/iis_virtual_directory_spec_test.rb'

# Offense count: 1
Lint/UselessAssignment:
  Exclude:
    - 'spec/support/utilities/utility_helper.rb'

# Offense count: 17
# Configuration parameters: AllowedMethods, AllowedPatterns, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 152

# Offense count: 13
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns, inherit_mode.
# AllowedMethods: refine
Metrics/BlockLength:
  Max: 443

# Offense count: 6
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/CyclomaticComplexity:
  Max: 15

# Offense count: 15
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
Metrics/MethodLength:
  Max: 60

# Offense count: 6
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/PerceivedComplexity:
  Max: 15

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: lowercase, uppercase
Naming/HeredocDelimiterCase:
  Exclude:
    - 'spec/acceptance/iis_unicode_site_spec.rb'

# Offense count: 1
# Configuration parameters: ForbiddenDelimiters.
# ForbiddenDelimiters: (?i-mx:(^|\s)(EO[A-Z]{1}|END)(\s|$))
Naming/HeredocDelimiterNaming:
  Exclude:
    - 'spec/acceptance/iis_minimal_config_spec.rb'

# Offense count: 8
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: as, at, by, cc, db, id, if, in, io, ip, of, on, os, pp, to
Naming/MethodParameterName:
  Exclude:
    - 'lib/puppet/type/iis_site.rb'
    - 'lib/puppet_x/puppetlabs/iis/bindings.rb'
    - 'lib/puppet_x/puppetlabs/iis/property/authenticationinfo.rb'
    - 'lib/puppet_x/puppetlabs/iis/property/positive_integer.rb'
    - 'lib/puppet_x/puppetlabs/iis/property/whole_number.rb'

# Offense count: 3
# Configuration parameters: NamePrefix, ForbiddenPrefixes, AllowedMethods, MethodDefinitionMacros.
# NamePrefix: is_, has_, have_
# ForbiddenPrefixes: is_, has_, have_
# AllowedMethods: is_a?
# MethodDefinitionMacros: define_method, define_singleton_method
Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'lib/puppet/provider/iis_common.rb'
    - 'lib/puppet/provider/iis_feature/default.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
Performance/StringInclude:
  Exclude:
    - 'spec/spec_helper_acceptance_local.rb'

# Offense count: 4
RSpec/AnyInstance:
  Exclude:
    - 'spec/unit/puppet_x/puppetlabs/iis/iis_version_spec.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
RSpec/BeEq:
  Exclude:
    - 'spec/unit/puppet_x/puppetlabs/iis/iis_version_spec.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: be_a, be_kind_of
RSpec/ClassCheck:
  Exclude:
    - 'spec/unit/puppet/provider/iis_virtual_directory/webadministration_spec.rb'
    - 'spec/unit/puppet/type/iis_site_spec.rb'

# Offense count: 69
# Configuration parameters: Prefixes, AllowedPatterns.
# Prefixes: when, with, without
RSpec/ContextWording:
  Exclude:
    - 'spec/acceptance/iis_application_pool_spec.rb'
    - 'spec/acceptance/iis_application_spec.rb'
    - 'spec/acceptance/iis_site_spec.rb'
    - 'spec/acceptance/iis_virtual_directory_spec.rb'
    - 'spec/acceptance/iis_virtual_directory_spec_test.rb'
    - 'spec/unit/puppet/provider/iis_site/webadministration_spec.rb'
    - 'spec/unit/puppet/provider/iis_virtual_directory/webadministration_spec.rb'
    - 'spec/unit/puppet/type/iis_application_pool_spec.rb'
    - 'spec/unit/puppet/type/iis_application_spec.rb'
    - 'spec/unit/puppet/type/iis_site_spec.rb'
    - 'spec/unit/puppet/type/iis_virtual_directory_spec.rb'

# Offense count: 18
# Configuration parameters: IgnoredMetadata.
RSpec/DescribeClass:
  Enabled: false

# Offense count: 17
# This cop supports unsafe autocorrection (--autocorrect-all).
RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/acceptance/iis_application_spec.rb'
    - 'spec/acceptance/iis_feature_spec.rb'
    - 'spec/acceptance/iis_minimal_config_spec.rb'
    - 'spec/acceptance/iis_site_spec.rb'
    - 'spec/acceptance/iis_virtual_directory_spec.rb'
    - 'spec/acceptance/iis_virtual_directory_spec_test.rb'

# Offense count: 20
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowConsecutiveOneLiners.
RSpec/EmptyLineAfterExample:
  Exclude:
    - 'spec/acceptance/iis_application_pool_spec.rb'
    - 'spec/acceptance/iis_application_spec.rb'
    - 'spec/acceptance/iis_site_spec.rb'
    - 'spec/unit/puppet/type/iis_application_pool_spec.rb'
    - 'spec/unit/puppet/type/iis_site_spec.rb'

# Offense count: 20
# This cop supports safe autocorrection (--autocorrect).
RSpec/EmptyLineAfterExampleGroup:
  Exclude:
    - 'spec/unit/puppet/provider/iis_application/webadministration_spec.rb'
    - 'spec/unit/puppet/type/iis_application_spec.rb'
    - 'spec/unit/puppet/type/iis_site_spec.rb'

# Offense count: 13
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowConsecutiveOneLiners.
RSpec/EmptyLineAfterHook:
  Exclude:
    - 'spec/acceptance/iis_site_spec.rb'
    - 'spec/acceptance/iis_unicode_site_spec.rb'
    - 'spec/acceptance/iis_virtual_directory_spec.rb'
    - 'spec/acceptance/iis_virtual_directory_spec_test.rb'
    - 'spec/unit/puppet/provider/iis_application/webadministration_spec.rb'

# Offense count: 39
# Configuration parameters: CountAsOne.
RSpec/ExampleLength:
  Max: 37

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
RSpec/ExcessiveDocstringSpacing:
  Exclude:
    - 'spec/acceptance/iis_site_spec.rb'

# Offense count: 1
# Configuration parameters: Include, CustomTransform, IgnoreMethods, SpecSuffixOnly.
# Include: **/*_spec*rb*, **/spec/**/*
RSpec/FilePath:
  Exclude:
    - 'spec/acceptance/iis_virtual_directory_spec_test.rb'

# Offense count: 39
# This cop supports safe autocorrection (--autocorrect).
RSpec/HooksBeforeExamples:
  Exclude:
    - 'spec/acceptance/iis_application_pool_spec.rb'
    - 'spec/acceptance/iis_application_spec.rb'
    - 'spec/acceptance/iis_site_spec.rb'
    - 'spec/acceptance/iis_unicode_site_spec.rb'
    - 'spec/acceptance/iis_virtual_directory_spec.rb'
    - 'spec/acceptance/iis_virtual_directory_spec_test.rb'

# Offense count: 1
# Configuration parameters: AssignmentOnly.
RSpec/InstanceVariable:
  Exclude:
    - 'spec/acceptance/iis_application_spec.rb'

# Offense count: 18
RSpec/MultipleExpectations:
  Max: 4

# Offense count: 9
# Configuration parameters: AllowSubject.
RSpec/MultipleMemoizedHelpers:
  Max: 8

# Offense count: 36
# Configuration parameters: AllowedGroups.
RSpec/NestedGroups:
  Max: 5

# Offense count: 76
# Configuration parameters: AllowedPatterns.
# AllowedPatterns: ^expect_, ^assert_
RSpec/NoExpectationExample:
  Exclude:
    - 'spec/acceptance/iis_application_pool_spec.rb'
    - 'spec/acceptance/iis_application_spec.rb'
    - 'spec/acceptance/iis_feature_spec.rb'
    - 'spec/acceptance/iis_site_spec.rb'
    - 'spec/acceptance/iis_virtual_directory_spec.rb'
    - 'spec/acceptance/iis_virtual_directory_spec_test.rb'
    - 'spec/support/utilities/utility_helper.rb'
    - 'spec/unit/puppet/provider/iis_application/webadministration_spec.rb'
    - 'spec/unit/puppet/provider/iis_virtual_directory/webadministration_spec.rb'
    - 'spec/unit/puppet/type/iis_site_spec.rb'
    - 'spec/unit/puppet/type/iis_virtual_directory_spec.rb'

# Offense count: 1
RSpec/PendingWithoutReason:
  Exclude:
    - 'spec/acceptance/iis_application_spec.rb'

# Offense count: 2
RSpec/RepeatedDescription:
  Exclude:
    - 'spec/acceptance/iis_application_pool_spec.rb'

# Offense count: 2
RSpec/RepeatedExampleGroupDescription:
  Exclude:
    - 'spec/acceptance/iis_application_pool_spec.rb'

# Offense count: 4
RSpec/StubbedMock:
  Exclude:
    - 'spec/unit/puppet/provider/iis_powershell_spec.rb'
    - 'spec/unit/puppet_x/puppetlabs/iis/iis_version_spec.rb'

# Offense count: 2
RSpec/UnspecifiedException:
  Exclude:
    - 'spec/acceptance/iis_unicode_site_spec.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: .
# SupportedStyles: constant, string
RSpec/VerifiedDoubleReference:
  EnforcedStyle: string

# Offense count: 12
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/puppet_x/puppetlabs/iis/bindings.rb'
    - 'lib/puppet_x/puppetlabs/iis/iis_features.rb'
    - 'lib/puppet_x/puppetlabs/iis/iis_version.rb'
    - 'lib/puppet_x/puppetlabs/iis/property/hash.rb'
    - 'lib/puppet_x/puppetlabs/iis/property/name.rb'
    - 'lib/puppet_x/puppetlabs/iis/property/path.rb'
    - 'lib/puppet_x/puppetlabs/iis/property/positive_integer.rb'
    - 'lib/puppet_x/puppetlabs/iis/property/read_only.rb'
    - 'lib/puppet_x/puppetlabs/iis/property/string.rb'
    - 'lib/puppet_x/puppetlabs/iis/property/timeformat.rb'
    - 'lib/puppet_x/puppetlabs/iis/property/whole_number.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/Dir:
  Exclude:
    - 'spec/spec_helper_local.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/ExpandPathArguments:
  Exclude:
    - 'lib/puppet/provider/iis_powershell.rb'

# Offense count: 6
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: MinBodyLength, AllowConsecutiveConditionals.
Style/GuardClause:
  Exclude:
    - 'lib/puppet/provider/iis_application/webadministration.rb'
    - 'lib/puppet/provider/iis_common.rb'
    - 'lib/puppet/provider/iis_powershell.rb'
    - 'lib/puppet/provider/iis_site/webadministration.rb'
    - 'spec/spec_helper_local.rb'

# Offense count: 49
# This cop supports safe autocorrection (--autocorrect).
Style/IfUnlessModifier:
  Exclude:
    - 'lib/puppet/provider/iis_application/webadministration.rb'
    - 'lib/puppet/provider/iis_common.rb'
    - 'lib/puppet/provider/iis_feature/default.rb'
    - 'lib/puppet/provider/iis_powershell.rb'
    - 'lib/puppet/provider/iis_site/webadministration.rb'
    - 'lib/puppet/type/iis_application.rb'
    - 'lib/puppet/type/iis_application_pool.rb'
    - 'lib/puppet/type/iis_site.rb'
    - 'lib/puppet/type/iis_virtual_directory.rb'
    - 'lib/puppet_x/puppetlabs/iis/property/path.rb'
    - 'spec/spec_helper_local.rb'

# Offense count: 1
Style/MixinUsage:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle, AllowedMethods, AllowedPatterns.
# SupportedStyles: predicate, comparison
Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'
    - 'lib/puppet_x/puppetlabs/iis/property/positive_integer.rb'

# Offense count: 2
# Configuration parameters: AllowedMethods.
# AllowedMethods: respond_to_missing?
Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/puppet/provider/iis_powershell.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: Methods.
Style/RedundantArgument:
  Exclude:
    - 'lib/puppet/provider/iis_application_pool/webadministration.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantAssignment:
  Exclude:
    - 'lib/puppet/provider/iis_application/webadministration.rb'
    - 'lib/puppet/provider/iis_application_pool/webadministration.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantConstantBase:
  Exclude:
    - 'lib/puppet/type/iis_application_pool.rb'
    - 'lib/puppet/type/iis_site.rb'

# Offense count: 12
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantRegexpEscape:
  Exclude:
    - 'lib/puppet/type/iis_site.rb'
    - 'lib/puppet_x/puppetlabs/iis/property/name.rb'
    - 'spec/acceptance/iis_site_spec.rb'

# Offense count: 13
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantStringEscape:
  Exclude:
    - 'lib/puppet/provider/iis_application_pool/webadministration.rb'
    - 'lib/puppet/type/iis_application.rb'
    - 'spec/acceptance/iis_application_pool_spec.rb'
    - 'spec/acceptance/iis_unicode_site_spec.rb'
    - 'spec/acceptance/iis_virtual_directory_spec.rb'
    - 'spec/acceptance/iis_virtual_directory_spec_test.rb'
    - 'spec/support/utilities/iis_site.rb'
    - 'spec/support/utilities/utility_helper.rb'

# Offense count: 21
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Exclude:
    - 'lib/puppet/provider/iis_application/webadministration.rb'
    - 'lib/puppet/provider/iis_common.rb'
    - 'lib/puppet/type/iis_application.rb'
    - 'lib/puppet/type/iis_site.rb'
    - 'lib/puppet_x/puppetlabs/iis/property/path.rb'
    - 'spec/acceptance/iis_application_spec.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: implicit, explicit
Style/RescueStandardError:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/spec_helper_local.rb'

# Offense count: 2
# This cop supports unsafe autocorrection (--autocorrect-all).
Style/SlicingWithRange:
  Exclude:
    - 'lib/puppet/provider/iis_application/webadministration.rb'

# Offense count: 4
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowModifier.
Style/SoleNestedConditional:
  Exclude:
    - 'lib/puppet/provider/iis_common.rb'
    - 'lib/puppet/type/iis_site.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: Mode.
Style/StringConcatenation:
  Exclude:
    - 'lib/puppet/provider/iis_feature/default.rb'

# Offense count: 42
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInHashLiteral:
  Exclude:
    - 'lib/puppet/provider/iis_application_pool/webadministration.rb'
    - 'lib/puppet/provider/iis_feature/default.rb'
    - 'spec/spec_helper.rb'
    - 'spec/unit/puppet/provider/iis_application/webadministration_spec.rb'
    - 'spec/unit/puppet/provider/iis_application_pool/webadministration_spec.rb'
    - 'spec/unit/puppet/provider/iis_site/webadministration_spec.rb'
    - 'spec/unit/puppet/type/iis_application_pool_spec.rb'
    - 'spec/unit/puppet/type/iis_application_spec.rb'
    - 'spec/unit/puppet/type/iis_site_spec.rb'
